# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gateway-api.local
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway-api
            port:
              number: 4000