# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  labels:
    app: gateway-api
spec:
  ports:
  - port: 4000
    targetPort: 3000
    protocol: TCP
  selector:
    app: gateway-api
  type: ClusterIP